### ISSUE TITLE
Configure fitting taxonomies

### ISSUE THREAD

**Issue by jneidel** [jneidel/jneidel.com#22]
Currently everything is tags.

Some tags I have are topics: crypto, Kleinanzeigen, challenge

Some tags are types of review: product review, media review

Setup:
```toml
[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'
```

[Docs](https://gohugo.io/content-management/taxonomies/)

- [ ] added taxonomies
- [ ] customized relevant listing pages
- [ ] overwrite ./_default/taxonomy.html to enable styling the h1
